# https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-apiversion-definition-guide.html
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo2-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo2
        env: dev
    spec:
      containers:
        - name: demo2
          image: storehub/demo2
          ports:
            - name: http-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: dev-config
---
apiVersion: v1
kind: Service
metadata:
  name: demo2
spec:
  selector:
    app: demo2
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80